# Generated by Django 6.0.5 on 2026-06-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('air_temperature_c', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('rainfall_mm', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('crop_health_index', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
