# Generated by Django 6.0.5 on 2026-06-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmdata',
            name='crop_duration_days',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='fertilizer_applied',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='growth_stage',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='irrigation_status',
            field=models.CharField(default='OFF', max_length=10),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='pest_risk_level',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='soil_temperature_c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='solar_radiation_wm2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='wind_speed_mps',
            field=models.FloatField(default=0),
        ),
    ]
